export const FETCH_FEED_SUCCESS = "FETCH_FEED_SUCCESS";
export const NEW_BATCH_SUCCESS = "NEW_BATCH_SUCCESS";
export const PIN_ARTICLE_REQUEST = "PIN_ARTICLE_REQUEST";
export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const RESET_ALL_STATE = "RESET_ALL_STATE";
